spring:
  application:
    name: job-config
  lifecycle:
    timeout-per-shutdown-phase: 30s
  profiles:
    active: prod,native
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  cloud:
    config:
      server:
        native:
          search-locations: file:///${BK_JOB_CONFIG_DIR}/job-common,file:///${BK_JOB_CONFIG_DIR}/job-gateway,file:///${BK_JOB_CONFIG_DIR}/job-manage,file:///${BK_JOB_CONFIG_DIR}/job-execute,file:///${BK_JOB_CONFIG_DIR}/job-logsvr,file:///${BK_JOB_CONFIG_DIR}/job-crontab,file:///${BK_JOB_CONFIG_DIR}/job-backup,file:///${BK_JOB_CONFIG_DIR}/job-file-gateway,file:///${BK_JOB_CONFIG_DIR}/job-ticket,file:///${BK_JOB_CONFIG_DIR}/job-analysis,file:///${BK_JOB_CONFIG_DIR}/job-assemble
management:
  health:
    # 使用spring cloud stream rabbitmq, 禁用掉springboot的rabbitmq health检查
    rabbit:
      enabled: false
  endpoints:
    web:
      exposure:
        include: health,configprops,env,beans,conditions,loggers,metrics,mappings,prometheus,scheduledtasks,info,refresh,busrefresh,bindings
      base-path: /actuator
    access:
      default: none
  endpoint:
    health:
      access: unrestricted
      show-details: when_authorized
      probes:
        enabled: true
    configprops:
      access: unrestricted
    env:
      access: unrestricted
    beans:
      access: unrestricted
    conditions:
      access: unrestricted
    loggers:
      access: unrestricted
    metrics:
      access: unrestricted
    mappings:
      access: unrestricted
    prometheus:
      access: unrestricted
    scheduledtasks:
      access: unrestricted
    info:
      access: unrestricted
    refresh:
      access: unrestricted
    busrefresh:
      access: unrestricted
server:
  port: 19801
  shutdown: graceful
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

