{{- if .Values.migration.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "common.names.fullname" . }}-migration-{{ .Release.Revision }}
  labels:
    {{- include "common.labels.standard" . | nindent 4 }}
    app.kubernetes.io/component: "job-migration"
    {{ include "job.labelKeys.imageTag" . }}: {{ .Values.migration.image.tag | quote }}
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
    {{- if .Values.commonAnnotations }}
    annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
      helm.sh/hook: pre-install,pre-upgrade
      helm.sh/hook-weight: "1"
      helm.sh/hook-delete-policy: hook-succeeded
    {{- end }}
spec:
  backoffLimit: 5
  template:
    metadata:
      labels:
        {{- include "common.labels.matchLabels" . | nindent 8 }}
        app.kubernetes.io/component: "job-migration"
    spec:
      hostAliases: {{- include "common.tplvalues.render" (dict "value" .Values.hostAliases "context" $) | nindent 8 }}
      initContainers:
        - name: wait-mariadb
          image: {{ include "common.images.image" (dict "imageRoot" .Values.migrationInit.image "global" .Values.global) }}
          imagePullPolicy: {{ .Values.migrationInit.image.pullPolicy }}
          command: ['sh', '-c', 'until nc -zw3 {{ include "job.mariadb.host" . }} {{ include "job.mariadb.port" . }}; do echo waiting for mariadb; sleep 2; done']
          resources:
            {{- toYaml .Values.migrationInit.resources | nindent 12 }}
      containers:
        - name: "job-migration"
          image: {{ include "job-migration.image" . }}
          imagePullPolicy: {{ .Values.migration.image.pullPolicy }}
          resources:
            {{- toYaml .Values.migration.resources | nindent 12 }}
          command: ["bash"]
          args: ["/data/job/exec/startup.sh"]
          env:
            - name: BK_JOB_MYSQL_HOST
              value: {{ include "job.mariadb.host" . | quote }}
            - name: BK_JOB_MYSQL_PORT
              value: {{ include "job.mariadb.port" . | quote }}
            - name: BK_JOB_MYSQL_ROOT_PASSWORD
              value: {{ include "job.mariadb.rootPassword" . | quote }}
            - name: BK_IAM_URL
              value: {{ .Values.bkIamApiUrl | quote }}
            - name: BK_JOB_APP_CODE
              value: {{ .Values.appCode | quote }}
            - name: BK_JOB_APP_SECRET
              value: {{ .Values.appSecret | quote }}
            - name: BK_JOB_API_URL
              value: {{ include "job.web.api.url" . }}
            - name: BK_JOB_MIGRATION_MYSQL_SCHEMA_ENABLED
              value: {{ .Values.job.migration.mysqlSchema.enabled | quote }}
            - name: BK_JOB_MIGRATION_IAM_MODEL_ENABLED
              value: {{ .Values.job.migration.iamModel.enabled | quote }}
      restartPolicy: Never
{{- end }}
