{{- if .Values.migration.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-%s" (include "job.fullname" .) "migration-db" }}
data:
  admin-username: {{ include "job.migration.mysqlSchema.adminUsername" . | b64enc | quote }}
  admin-password: {{ include "job.migration.mysqlSchema.adminPassword" . | b64enc | quote }}
type: Opaque
{{- end }}