{{- if .Values.crontabConfig.database.host }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "job.crontabdb.secretName" . }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  namespace: {{ .Release.Namespace }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
type: Opaque
data:
  crontab-db-password: {{ .Values.crontabConfig.database.password | b64enc | quote }}
{{- end }}
