{{- if and (not .Values.mariadb.enabled) (not .Values.externalMariaDB.existingPasswordSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-%s" (include "job.fullname" .) "external-mariadb" }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  namespace: {{ .Release.Namespace }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
type: Opaque
data:
  mariadb-password: {{ .Values.externalMariaDB.password | b64enc | quote }}
  mariadb-truststore-password: {{ .Values.externalMariaDB.tls.trustStorePassword | b64enc | quote }}
  mariadb-keystore-password: {{ .Values.externalMariaDB.tls.keyStorePassword | b64enc | quote }}
{{- end }}
