{{- if .Values.migration.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-%s" (include "job.fullname" .) "migrate-db" }}
data:
  admin-username: {{ include "job.mariadb.adminUsername" . | b64enc | quote }}
  admin-password: {{ include "job.mariadb.adminPassword" . | b64enc | quote }}
type: Opaque
{{- end }}