USE `job_manage`;

DELETE FROM `job_manage`.`analysis_task_static_instance` where id in (1,2,3,4,5);

REPLACE INTO `job_manage`.`analysis_task_static_instance`(`id`, `app_id`, `task_id`, `status`, `result_data`, `result_data_en`, `priority`, `active`, `creator`, `last_modify_user`, `create_time`, `last_modify_time`) VALUES (1, -1, -1, 2, '使用作业平台 Shell 脚本的内置函数 `job_success` `job_fail`，可以轻松实现简单的执行结果归类分组效果；更多使用技巧，详见[文档](${BK_DOCS_CENTER}/markdown/作业平台/产品白皮书/Best-Practices/Use-built-in-functions-to-make-exec-result-grouping.md)', 'Using built-in functions `job_success` `job_fail`, execution results can be grouped easily. Find out more tips with [Docs](${BK_DOCS_CENTER}/markdown/作业平台/产品白皮书/Best-Practices/Use-built-in-functions-to-make-exec-result-grouping.md)', 100, b'1', 'admin', 'admin', 1583492717314, 1583492717318);
REPLACE INTO `job_manage`.`analysis_task_static_instance`(`id`, `app_id`, `task_id`, `status`, `result_data`, `result_data_en`, `priority`, `active`, `creator`, `last_modify_user`, `create_time`, `last_modify_time`) VALUES (2,  -1, -1, 2, '如何让同一批主机在不同的步骤中享有独立的变量空间？这样在应对多批次机器执行同一场景时，而无需设置过多的字符串变量或数组索引；详见[文档](${BK_DOCS_CENTER}/markdown/作业平台/产品白皮书/Best-Practices/How-to-make-same-host-have-its-own-namespace.md)', 'How to make bunch of hosts own its independent variable space in different steps? In this way, when dealing with multiple hosts to execute the same scene, not necessary to set too many string variables or array indexes. For more information see [Docs](${BK_DOCS_CENTER}/markdown/作业平台/产品白皮书/Best-Practices/How-to-make-same-host-have-its-own-namespace.md)', 100, b'1', 'admin', 'admin', 1583492717314, 1583492717318);
REPLACE INTO `job_manage`.`analysis_task_static_instance`(`id`, `app_id`, `task_id`, `status`, `result_data`, `result_data_en`, `priority`, `active`, `creator`, `last_modify_user`, `create_time`, `last_modify_time`) VALUES (3,  -1, -1, 2, '脚本传参涉及到敏感信息（如密码）该如何规避因明文传输而导致信息泄露的风险？`密文` 变量可以帮你解决这个问题！', 'Params involves sensitive information (such as passwords). How to avoid the risk of information leakage? The `Ciphertext` variable can help you solve this problem!', 100, b'1', 'admin', 'admin', 1583492717314, 1583492717318);
REPLACE INTO `job_manage`.`analysis_task_static_instance`(`id`, `app_id`, `task_id`, `status`, `result_data`, `result_data_en`, `priority`, `active`, `creator`, `last_modify_user`, `create_time`, `last_modify_time`) VALUES (4,  -1, -1, 2, '为你的作业模板设置一个标签可以方便你更好的进行分类管理，在「作业」页面左侧可以快速通过分类标签找到你的作业模板。', 'Job tags can help you manage template classification better, you can easily toggle different tags in left side on Jobs page.', 100, b'1', 'admin', 'admin', 1583492717314, 1583492717318);
REPLACE INTO `job_manage`.`analysis_task_static_instance`(`id`, `app_id`, `task_id`, `status`, `result_data`, `result_data_en`, `priority`, `active`, `creator`, `last_modify_user`, `create_time`, `last_modify_time`) VALUES (5,  -1, -1, 2, '收藏的作业除了可以在列表中置顶，还会显示到首页中，这样你就能更快的找到你常用的作业了。', 'Favorited Jobs can be displayed on the top of the Job list, also in HOME page, so you can found it faster when you need it.', 100, b'1', 'admin', 'admin', 1583492717314, 1583492717318);
REPLACE INTO `job_manage`.`analysis_task_static_instance`(`id`, `app_id`, `task_id`, `status`, `result_data`, `result_data_en`, `priority`, `active`, `creator`, `last_modify_user`, `create_time`, `last_modify_time`) VALUES (6,  -1, -1, 2, '你知道么，Shell 也支持数组变量喔~ 写法示例： `var[0]=\'test1\'; var[1]=\'test2\';` 通过 `echo ${var[*]}` 可以打印变量的所有索引值，`echo ${#var[*]}` 可以打印变量一共有多少个索引。', 'You know what, Array variable is supported in Bash. How? `var[0]=\'test1\'; var[1]=\'test2\';` and using `echo ${var[*]}` to print all index values of Array variable, using `echo ${#var[*]}` to show how many index the Array variable has.', 100, b'1', 'admin', 'admin', 1583492717314, 1583492717318);
REPLACE INTO `job_manage`.`analysis_task_static_instance`(`id`, `app_id`, `task_id`, `status`, `result_data`, `result_data_en`, `priority`, `active`, `creator`, `last_modify_user`, `create_time`, `last_modify_time`) VALUES (7,  -1, -1, 2, '当发现某个线上脚本出现严重漏洞时，如何快速止损？脚本版本管理的 `禁用` 可以帮到你，详见[文档](${BK_DOCS_CENTER}/markdown/作业平台/产品白皮书/Best-Practices/How-to-stop-the-spread-of-the-problem-script-immediately.md)', 'How to stop loss immediately when a serious bug in an online script is found? You can set the version status to `BANNED` in script version management. See [Docs](${BK_DOCS_CENTER}/markdown/作业平台/产品白皮书/Best-Practices/How-to-stop-the-spread-of-the-problem-script-immediately.md)', 100, b'1', 'admin', 'admin', 1583492717314, 1583492717318);
