spring:
  application:
    name: job-manage
  datasource:
    job-manage:
      driver-class-name: io.opentelemetry.instrumentation.jdbc.OpenTelemetryDriver
      type: com.zaxxer.hikari.HikariDataSource
      jdbc-url: jdbc:otel:mysql://__BK_JOB_MANAGE_MYSQL_HOST__:__BK_JOB_MANAGE_MYSQL_PORT__/job_manage?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull
      username: __BK_JOB_MANAGE_MYSQL_USERNAME__
      password: __BK_JOB_MANAGE_MYSQL_PASSWORD__
      maximum-pool-size: 100
      minimum-idle: 20
      idle-timeout: 600000
      poolName: "job-manage"
      validationTimeout: 5000

  rabbitmq:
    host: __BK_JOB_MANAGE_RABBITMQ_HOST__
    port: __BK_JOB_MANAGE_RABBITMQ_PORT__
    username: __BK_JOB_MANAGE_RABBITMQ_USERNAME__
    password: __BK_JOB_MANAGE_RABBITMQ_PASSWORD__
    virtual-host: __BK_JOB_MANAGE_RABBITMQ_VHOST__
  redis:
    {# 社区版默认配置 -#}
    {% if job_edition != "ee" -%}
    # 使用单机Redis时的配置项
    host: __BK_JOB_MANAGE_REDIS_HOST__
    port: __BK_JOB_MANAGE_REDIS_PORT__
    # 使用Redis Sentinel时的配置项
    #sentinel:
      #password: __BK_JOB_MANAGE_REDIS_SENTINEL_PASSWORD__
      #master: __BK_JOB_MANAGE_REDIS_SENTINEL_MASTER__
      #nodes: __BK_JOB_MANAGE_REDIS_SENTINEL_NODES__
    {% endif -%}
    {# 企业版默认配置 -#}
    {% if job_edition == "ee" -%}
    # 使用单机Redis时的配置项
    #host: __BK_JOB_MANAGE_REDIS_HOST__
    #port: __BK_JOB_MANAGE_REDIS_PORT__
    # 使用Redis Sentinel时的配置项
    sentinel:
      password: __BK_JOB_MANAGE_REDIS_SENTINEL_PASSWORD__
      master: __BK_JOB_MANAGE_REDIS_SENTINEL_MASTER__
      nodes: __BK_JOB_MANAGE_REDIS_SENTINEL_NODES__
    {% endif -%}
    password: __BK_JOB_MANAGE_REDIS_PASSWORD__
    database: 0
    lettuce:
      pool:
        min-idle: 5
        max-idle: 10
        max-active: 8
        max-wait: 1ms
      shutdown-timeout: 100ms
  servlet:
    multipart:
      max-file-size: 5GB
      max-request-size: 5GB

bk:
  {% if job_edition == "ce" -%}
  doc:
    # 首页右上角产品文档根地址
    root: https://bk.tencent.com/docs
  {% endif -%}
  feedback:
    # 首页右上角问题反馈链接
    root:
  helper:
    # 首页底部联系BK助手的跳转URL（可为企业微信URL）
    url: wxwork://message?uin=8444252571319680
job:
  manage:
    sync:
      app:
        enabled: true
      host:
        enabled: true
      resource:
        watch:
          enabled: true
      hostEvent:
        # 开启CMDB事件监听时用于处理主机事件的线程数量，一般情况下无须修改
        # 当环境中主机事件平均产生速率较高（>10/s）或主机信息相比于CMDB数据经常性明显滞后（分钟级）时，可增大该数值
        handlerNum: 3
notify:
  default:
    channels:
      available: mail

