spring:
  application:
    name: job-logsvr
  profiles:
    active: prod
  data:
    mongodb:
      uri: __BK_JOB_LOGSVR_MONGODB_URI__
  cloud:
    consul:
      discovery:
        service-name: 'job-logsvr'
        instance-id: job-logsvr-${machine.ip}-${server.port}
        enabled: true
        prefer-ip-address: true
    stream:
      defaultBinder: jobCommon
      binders:
        jobCommon:
          type: rabbit
          environment:
            spring:
              rabbitmq:
                host: __BK_JOB_RABBITMQ_HOST__
                port: __BK_JOB_RABBITMQ_PORT__
                username: __BK_JOB_RABBITMQ_USERNAME__
                password: __BK_JOB_RABBITMQ_PASSWORD__
                virtual-host: __BK_JOB_RABBITMQ_VHOST__
job:
  logsvr:
    mongodb:
      shard:
        enabled: false
        
server:
  port: __BK_JOB_LOGSVR_SERVER_PORT__
