spring:
  cloud:
    stream:
      defaultBinder: jobCommon
      binders:
        jobCommon:
          type: rabbit
          environment:
            spring:
              rabbitmq:
                host: __BK_JOB_RABBITMQ_HOST__
                port: __BK_JOB_RABBITMQ_PORT__
                username: __BK_JOB_RABBITMQ_USERNAME__
                password: __BK_JOB_RABBITMQ_PASSWORD__
                virtual-host: __BK_JOB_RABBITMQ_VHOST__
    gateway:
      routes:
        - id: job-logout
          uri: lb://job-gateway
          predicates:
            - Path= /logout
          filters:
            - Logout
        - id: job-manage-web
          uri: lb://job-manage
          predicates:
            - Path= /job-manage/web/**
          filters:
            - Authorize
            - CsrfCheck
            - StripPrefix=1
            - AddWebLangHeader
        - id: job-crontab-web
          uri: lb://job-crontab
          predicates:
            - Path= /job-crontab/web/**
          filters:
            - Authorize
            - CsrfCheck
            - StripPrefix=1
            - AddWebLangHeader
        - id: job-execute-web
          uri: lb://job-execute
          predicates:
            - Path= /job-execute/web/**
          filters:
            - Authorize
            - CsrfCheck
            - StripPrefix=1
            - AddWebLangHeader
        - id: job-backup-web
          uri: lb://job-backup
          predicates:
            - Path= /job-backup/web/**
          filters:
            - Authorize
            - CsrfCheck
            - StripPrefix=1
            - AddWebLangHeader
        - id: job-file-gateway-web
          uri: lb://job-file-gateway
          predicates:
            - Path= /job-file-gateway/web/**
          filters:
            - Authorize
            - CsrfCheck
            - StripPrefix=1
            - AddWebLangHeader
        - id: job-ticket-web
          uri: lb://job-manage
          predicates:
            - Path= /job-ticket/web/**
          filters:
            - Authorize
            - CsrfCheck
            - StripPrefix=1
            - AddWebLangHeader
        - id: job-analysis-web
          uri: lb://job-analysis
          predicates:
            - Path= /job-analysis/web/**
          filters:
            - Authorize
            - CsrfCheck
            - StripPrefix=1
            - AddWebLangHeader

        - id: job-file-gateway-remote
          uri: lb://job-file-gateway
          predicates:
            - Path= /job-file-gateway/remote/**
          filters:
            - AuthorizeRemote
            - StripPrefix=1

        - id: job-manage-esb
          uri: lb://job-manage
          predicates:
            - JobEsbV2Path=/api/job/v2/job-manage/{api_name}
          filters:
            - CheckEsbJwt
            - SetPath=/esb/api/v2/{api_name}
            - RecordEsbAccessLog
            - AddEsbLangHeader

        - id: job-manage-esb-v3
          uri: lb://job-manage
          predicates:
            - Path=/api/job/v3/job-manage/{api_name}
          filters:
            - CheckEsbJwt
            - SetPath=/esb/api/v3/{api_name}
            - RecordEsbAccessLog
            - AddEsbLangHeader

        - id: job-crontab-esb
          uri: lb://job-crontab
          predicates:
            - JobEsbV2Path=/api/job/v2/job-crontab/{api_name}
          filters:
            - CheckEsbJwt
            - SetPath=/esb/api/v2/{api_name}
            - RecordEsbAccessLog
            - AddEsbLangHeader

        - id: job-crontab-esb-v3
          uri: lb://job-crontab
          predicates:
            - JobEsbV2Path=/api/job/v3/job-crontab/{api_name}
          filters:
            - CheckEsbJwt
            - SetPath=/esb/api/v3/{api_name}
            - RecordEsbAccessLog
            - AddEsbLangHeader

        - id: job-execute-esb
          uri: lb://job-execute
          predicates:
            - JobEsbV2Path=/api/job/v2/job-execute/{api_name}
          filters:
            - CheckEsbJwt
            - SetPath=/esb/api/v2/{api_name}
            - RecordEsbAccessLog
            - AddEsbLangHeader

        - id: job-execute-esb-v3
          uri: lb://job-execute
          predicates:
            - JobEsbV2Path=/api/job/v3/job-execute/{api_name}
          filters:
            - CheckEsbJwt
            - SetPath=/esb/api/v3/{api_name}
            - RecordEsbAccessLog
            - AddEsbLangHeader

        - id: job-file-gateway-esb-v3
          uri: lb://job-file-gateway
          predicates:
            - JobEsbV2Path=/api/job/v3/job-file-gateway/{api_name}
          filters:
            - CheckEsbJwt
            - SetPath=/esb/api/v3/{api_name}
            - RecordEsbAccessLog
            - AddEsbLangHeader

        - id: job-file-gateway-iam
          uri: lb://job-file-gateway
          predicates:
            - Path=/iam/api/v1/resources/file_source
          filters:
            - RecordIamAccessLog
            - AddEsbLangHeader

        - id: job-ticket-iam
          uri: lb://job-manage
          predicates:
            - Path=/iam/api/v1/resources/ticket
          filters:
            - RecordIamAccessLog
            - AddEsbLangHeader

        - id: job-analysis-iam
          uri: lb://job-analysis
          predicates:
            - Path=/iam/api/v1/resources/dashboard_view
          filters:
            - RecordIamAccessLog
            - AddEsbLangHeader

        - id: job-manage-iam
          uri: lb://job-manage
          predicates:
            - Path=/iam/api/v1/resources/script,/iam/api/v1/resources/task/template,/iam/api/v1/resources/task/plan,/iam/api/v1/resources/account,/iam/api/v1/resources/whitelist,/iam/api/v1/resources/script/public,/iam/api/v1/resources/tag
          filters:
            - RecordIamAccessLog
            - AddEsbLangHeader

        - id: job-crontab-iam
          uri: lb://job-crontab
          predicates:
            - Path=/iam/api/v1/resources/cron/job
          filters:
            - RecordIamAccessLog
            - AddEsbLangHeader

        - id: job-execute-iam
          uri: lb://job-execute
          predicates:
            - Path=/iam/api/v1/resources/execute/record
          filters:
            - RecordIamAccessLog
            - AddEsbLangHeader
server:
  http:
    enabled: __BK_JOB_GATEWAY_SERVER_HTTP_ENABLED__
    port: __BK_JOB_GATEWAY_SERVER_HTTP_PORT__
  ssl:
    enabled: true
    key-store-type: __BK_JOB_GATEWAY_SERVER_SSL_KEYSTORE_TYPE__
    key-store: file:__BK_CERT_PATH__/job_server.p12
    key-store-password: __BK_JOB_GATEWAY_SERVER_SSL_KEYSTORE_PASSWORD__
    key-alias: __BK_JOB_GATEWAY_SERVER_SSL_KEY_ALIAS__
    trust-store: file:__BK_CERT_PATH__/job_server.truststore
    trust-store-password: __BK_JOB_GATEWAY_SERVER_SSL_TRUSTSTORE_PASSWORD__
management:
  server:
    port: __BK_JOB_GATEWAY_SERVER_MANAGEMENT_PORT__