spring:
  cloud:
    consul:
      host: 127.0.0.1
      port: __CONSUL_HTTP_PORT__
      scheme: __CONSUL_SCHEME__
      enabled: true
      discovery:
        prefer-ip-address: true
        service-name: job-file-gateway
        instance-id: job-file-gateway-${machine.ip}-${server.port}
        scheme: http
        enabled: true
      #tls:
        #key-store-instance-type:
        #key-store-path:
        #key-store-password:
        #certificate-path:
        #certificate-password:
    config:
      discovery:
        enabled: true
        service-id: job-config
      username: __BK_JOB_SECURITY_USERNAME__
      password: __BK_JOB_SECURITY_PASSWORD__
      enabled: true
      fail-fast: true
