spring:
  cloud:
    stream:
      bindings:
        springCloudBusInput:
          destination: springCloudBus
          binder: jobCommon
        springCloudBusOutput:
          destination: springCloudBus
          binder: jobCommon
      binders:
        jobCommon:
          type: rabbit
          environment:
            spring:
              rabbitmq:
                host: __BK_JOB_RABBITMQ_HOST__
                port: __BK_JOB_RABBITMQ_PORT__
                username: __BK_JOB_RABBITMQ_USERNAME__
                password: __BK_JOB_RABBITMQ_PASSWORD__
                virtual-host: __BK_JOB_RABBITMQ_VHOST__
server:
  http:
    enabled: __BK_JOB_GATEWAY_SERVER_HTTP_ENABLED__
    port: __BK_JOB_GATEWAY_SERVER_HTTP_PORT__
  ssl:
    enabled: true
    key-store-type: __BK_JOB_GATEWAY_SERVER_SSL_KEYSTORE_TYPE__
    key-store: file:__BK_CERT_PATH__/job_server.p12
    key-store-password: __BK_JOB_GATEWAY_SERVER_SSL_KEYSTORE_PASSWORD__
    key-alias: __BK_JOB_GATEWAY_SERVER_SSL_KEY_ALIAS__
    trust-store: file:__BK_CERT_PATH__/job_server.truststore
    trust-store-password: __BK_JOB_GATEWAY_SERVER_SSL_TRUSTSTORE_PASSWORD__
