spring:
  main:
    allow-bean-definition-overriding: true
  lifecycle:
    timeout-per-shutdown-phase: 30s
  profiles:
    active: prod
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
management:
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true
    # 使用spring cloud stream rabbitmq, 禁用掉springboot的rabbitmq health检查
    rabbit:
      enabled: false
  endpoints:
    web:
      exposure:
        include: health,configprops,env,beans,conditions,loggers,metrics,mappings,prometheus,scheduledtasks,info,refresh,busrefresh,bindings
      base-path: /actuator
    access:
      default: none
  endpoint:
    health:
      access: unrestricted
      show-details: when_authorized
      probes:
        enabled: true
    configprops:
      access: unrestricted
    env:
      access: unrestricted
    beans:
      access: unrestricted
    conditions:
      access: unrestricted
    loggers:
      access: unrestricted
    metrics:
      access: unrestricted
    mappings:
      access: unrestricted
    prometheus:
      access: unrestricted
    scheduledtasks:
      access: unrestricted
    info:
      access: unrestricted
    refresh:
      access: unrestricted
    busrefresh:
      access: unrestricted
server:
  port: 19803
  shutdown: graceful
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true




