{{- if .Values.analysisConfig.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: job-analysis
  namespace: {{ .Release.Namespace }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    app.kubernetes.io/component: "job-analysis"
    {{ include "job.labelKeys.jobScope" . }}: {{ include "job.labelValues.jobScope.backend" . }}
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.analysisConfig.service.type }}
  ports:
    - name: http
      port: {{ .Values.analysisConfig.service.port }}
      targetPort: {{ .Values.analysisConfig.containerPort }}
      protocol: TCP
  selector: {{- include "common.labels.matchLabels" . | nindent 4 }}
    app.kubernetes.io/component: "job-analysis"
{{- end }}
