spring:
  application:
    name: job-logsvr
  profiles:
    active: prod
  data:
    mongodb:
      uri: ${job.logsvr.mongodb.uri}
  security:
    user:
      name: ${job.security.actuator.user.name}
      password: ${job.security.actuator.user.password}
      roles: ENDPOINT_ADMIN
job:
  security:
    service:
      private-key-base64: ${job.security.private-key-base64}
      public-key-base64: ${job.security.public-key-base64}

ribbon:
  ServerListRefreshInterval: 3000

management:
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health,configprops,env,beans,conditions,loggers,metrics,mappings,prometheus,scheduledtasks,info
      base-path: /actuator
    enabled-by-default: false
  endpoint:
    health:
      enabled: true
      show-details: when_authorized
      probes:
        enabled: true
    configprops:
      enabled: true
    env:
      enabled: true
    beans:
      enabled: true
    conditions:
      enabled: true
    loggers:
      enabled: true
    metrics:
      enabled: true
    mappings:
      enabled: true
    prometheus:
      enabled: true
    scheduledtasks:
      enabled: true
    info:
      enabled: true
server:
  port: 19806
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  shutdown: graceful

