spring:
  application:
    name: bk-job-op
  profiles:
    active: dev
  datasource:
    url: jdbc:mysql://${GCS_MYSQL_HOST:127.0.0.1}:${GCS_MYSQL_PORT:3306}/${GCS_MYSQL_NAME:job_op}?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull
    username: ${GCS_MYSQL_USER:root}
    password: ${GCS_MYSQL_PASSWORD:password}
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:
      host: ${BK_PAAS_REDIS_HOST:127.0.0.1}
      port: ${BK_PAAS_REDIS_PORT:6379}
      password: ${BK_PAAS_REDIS_PASSWORD:password}
      database: 0
      lettuce:
        pool:
          min-idle: 5
          max-idle: 10
          max-active: 8
          max-wait: 1ms
        shutdown-timeout: 100ms
  ai:
    mcp:
      server:
        name: bk-job-op    # MCP服务器名称
        version: 1.0.0                # 服务器版本号
        type: ASYNC #异步
        stdio: false
        protocol: STREAMABLE
        streamable-http:
          mcp-endpoint: /mcp
          keep-alive-interval: 15s

# HTTP客户端配置
http:
  client:
    # 连接超时时间（秒）
    connect-timeout: 10
    # 读取超时时间（秒）
    read-timeout: 60

# Spring Boot Actuator 配置
management:
  endpoints:
    web:
      exposure:
        include: health,info,env,metrics,beans,configprops
      base-path: /actuator
  endpoint:
    health:
      show-details: when-authorized
  info:
    env:
      enabled: true

# MCP认证配置
mcp:
  # 认证token
  auth:
    enabled: true
    apiKey: "api-key"

# API 认证配置
api:
  auth:
    apiKey: "job-op-api-key"

# BK API网关统一配置
bkApiGateway:
  # 默认apigw认证信息（默认正式环境的，若是想调用个别别的环境的网关，使用子项覆盖）
  bkAppCode: "bk-job-op"
  bkAppSecret: "bk-job-op-secret"
  
  # 调用bklog网关的配置
  bkLog:
    url: bklog.com
    retry-count: 3
    retry-interval: 3

bk:
  # BK-Log配置（多日志源）
  log:
    defaultSource: prod-service
    sources:
      prod-service:
        label: "生产环境-微服务日志"
        sortField: "log_time"
        indices: ""
        indexSetId: 100
        expireTime: 7
#      prod-gateway-access:
#        label: "生产环境-网关Access日志"
#        sortField: "time"
#        indices: ""
#        indexSetId: 101
#        expireTime: 7
#      prod-stdout:
#        label: "生产环境-标准输出日志"
#        sortField: "log_time"
#        indices: ""
#        indexSetId: 102
#        expireTime: 7
#      stag-service:
#        label: "预发布环境-微服务日志"
#        sortField: "log_time"
#        indices: ""
#        indexSetId: 200
#        expireTime: 7
