swagger: '2.0'
basePath: /
info:
  version: '0.1'
  title: API Gateway Resources
  description: ''
schemes:
  - http
paths:
  /v2/jobv3/fast_execute_script:
    get:
      operationId: fast_execute_script
      description: '快速执行脚本'
      tags: []
      responses:
        default:
          description: ''
      x-bk-apigateway-resource:
        isPublic: false
        allowApplyPermission: false
        matchSubpath: false
        backend:
          # name: default 支持设置 backend, 默认不配置为 default，和 stage 的 backends 配置的后端服务 name 一致
          type: HTTP
          method: post
          path: /api/job/v3/job-execute/fast_execute_script
          matchSubpath: false
          timeout: 0
          upstreams: {}
          transformHeaders: {}
        authConfig:
          appVerifiedRequired: true
          userVerifiedRequired: false
          resourcePermissionRequired: false
        descriptionEn:
