spring:
  profiles:
    active: prod
  servlet:
    multipart:
      max-file-size: 5GB
      max-request-size: 5GB
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

management:
  endpoints:
    web:
      exposure:
        include: health,configprops,env,beans,conditions,loggers,metrics,mappings,prometheus,scheduledtasks,info
      base-path: /actuator
    access:
      default: none
  endpoint:
    health:
      access: unrestricted
    configprops:
      access: unrestricted
    env:
      access: unrestricted
    beans:
      access: unrestricted
    conditions:
      access: unrestricted
    loggers:
      access: unrestricted
    metrics:
      access: unrestricted
    mappings:
      access: unrestricted
    prometheus:
      access: unrestricted
    scheduledtasks:
      access: unrestricted
    info:
      access: unrestricted
  metrics:
    tags:
      application: ${spring.application.name}

server:
  port: ${job.file-worker.access.port:19810}
  shutdown: graceful
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

job:
  file-worker:
    enabled-file-source-types: BLUEKING_ARTIFACTORY
